sets.exported={
    main={ name="Keraunos", augments={'"Mag.Atk.Bns."+15','"Refresh"+1','INT+8',}},
    sub="Niobid Strap",
    ammo="Dosis Tathlum",
    head="Arbatel Bonnet",
    body="Jhakri Robe +1",
    hands={ name="Amalric Gages", augments={'INT+10','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    legs={ name="Merlinic Shalwar", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','"Fast Cast"+3','"Mag.Atk.Bns."+14',}},
    feet="Arbatel Loafers",
    neck="Twilight Torque",
    waist="Fucho-no-Obi",
    left_ear="Enchntr. Earring +1",
    right_ear="Loquac. Earring",
    left_ring="Renaye Ring",
    right_ring={ name="Dark Ring", augments={'Phys. dmg. taken -3%','Breath dmg. taken -4%','Magic dmg. taken -4%',}},
    back={ name="Mecisto. Mantle", augments={'Cap. Point+42%','HP+13','DEF+6',}},
}