sets.exported={
    main="Denouements",
    range="Divinator",
    head={ name="Pitre Taj", augments={'Enhances "Optimization" effect',}},
    body={ name="Taeon Tabard", augments={'Accuracy+20 Attack+20','"Triple Atk."+2','Weapon skill damage +2%',}},
    hands="Count's Cuffs",
    legs={ name="Desultor Tassets", augments={'Phys. dmg. taken -4%','Movement speed +8%+2',}},
    feet={ name="Taeon Boots", augments={'Accuracy+24','"Triple Atk."+2','Crit. hit damage +2%',}},
    neck="Twilight Torque",
    waist="Fotia Belt",
    left_ear="Steelflash Earring",
    right_ear="Enchntr. Earring +1",
    left_ring="Renaye Ring",
    right_ring={ name="Dark Ring", augments={'Phys. dmg. taken -3%','Breath dmg. taken -4%','Magic dmg. taken -4%',}},
    back={ name="Mecisto. Mantle", augments={'Cap. Point+42%','HP+13','DEF+6',}},
}